### ISSUE TITLE
Invalid URL for KoDa API documentation

### ISSUE THREAD

**Issue by nelsonaelam** [trafiklab/openApi-docs#3]
I'm trying to read the documentation for the KoDa API at the URL listed [here](https://github.com/trafiklab/openApi-docs/blob/master/koda_api_v2.yaml) on line 14 but I'm getting a 404 error when trying to navigate to that page.

Is there another place this API is documented? I'm trying to understand some of the values listed in some of the files, specifically pickup_type, drop_off_type, shape_dist_traveled, and timepoint. 

Ultimately, I'm trying to figure out how to find delays and cancellations and I'm hoping some of these values contain that information. Thanks!

**Comment by Bertware** [comment]
Hi,

The files stored in KoDa are normal GTFS and GTFS-RT files from Trafiklabs GTFS Regional datasets. These are documented at trafiklab.se: https://www.trafiklab.se/api/gtfs-datasets/overview/static-data/ .
The GTFS format has its own website, which can be found at [gtfs.org](https://gtfs.org).
